backend:
  name: github
  repo: kwonjounghun/gatsby_blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: _posts/blog
    category: default
    create: true
    fields:
      - { name: path, label: Path, default: "/blog/" }
      - { name: label, label: Label, widget: hidden, default: "Blog" }
      - { name: category, label: Category, widget: select, options: ["post", "start", "first"]}
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: file, default: "/assets/sub06_contents02.jpg" }
      - { label: "public", name: "Public", widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }
  - name: study
    label: Study
    folder: _posts/study
    category: default
    create: true
    fields:
      - { name: path, label: Path, default: "/study/" }
      - { name: label, label: Label, widget: hidden, default: "Study" }
      - { name: category, label: Category, widget: select, options: ["post2", "start2", "first2"]}
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: file, default: "/assets/sub06_contents02.jpg" }
      - { label: "public", name: "Public", widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }
  - name: project
    label: Project
    folder: _posts/project
    category: default
    create: true
    fields:
      - { name: path, label: Path, default: "/project/" }
      - { name: label, label: Label, widget: hidden, default: "Project" }
      - { name: category, label: Category, widget: select, options: ["StarTeacher"]}
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: file, default: "/assets/sub06_contents02.jpg" }
      - { label: "public", name: "Public", widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }